language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules # Cache node_modules for faster builds

script:
  - npm install
  - npm test -- --coverage --watchAll=false # Run tests with coverage
  - npm run build # Create a production build

after_script:
  - npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
