language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules # Cache node_modules for faster builds

before_script:
  - cd client

script:
  - npm install
  - npm test # Run tests
  - npm run build # Create a production build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
